const headers = [
	{ text: '#', align: 'start', sortable: true, value: 'number'},
	{ text: 'дата', align: 'start', sortable: true, value: 'date'},
	{ text: 'уровень', align: 'start', sortable: true, value: 'level'},
	{ text: 'модуль', align: 'start', sortable: true, value: 'module'},
	{ text: 'описание', align: 'start', sortable: true, value: 'descr'},
]

const notifications = [
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
	{ number: 1, date: '01.12.19', level: 'error', module: 'worker service', descr: 'fooo' },
]

export {
	headers,
	notifications,
}
